package repositories

type CompRepositories interface {
	CountUsers() (int, error)
	CountUsersLastMonth() (int, error)
	CountComplaints() (int, error)
	CountComplaintsLastMonth() (int, error)
	CountComplaintsByStatus(status string) (int, error)
	CountComplaintsByStatusLastMonth(status string) (int, error)
	CountSchedules() (int, error)
	CountSchedulesLastMonth() (int, error)
	CountAnnouncements() (int, error)
	CountAnnouncementsLastMonth() (int, error)
	CountUMKM() (int, error)
	CountUMKMLastMonth() (int, error)
	CountUMKMProducts() (int, error)
	CountUMKMProductsLastMonth() (int, error)
	CountGalleries() (int, error)
	CountGalleriesLastMonth() (int, error)
	CountImages() (int, error)
	CountImagesLastMonth() (int, error)
	CountVideos() (int, error)
	CountVideosLastMonth() (int, error)
	CountNews() (int, error)
	CountNewsLastMonth() (int, error)
	CountFiles() (int, error)
	CountFilesLastMonth() (int, error)
}
