// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"gorm.io/gorm"
	controllers4 "kutamukti-api/api/announcement/controllers"
	repositories4 "kutamukti-api/api/announcement/repositories"
	services4 "kutamukti-api/api/announcement/services"
	controllers2 "kutamukti-api/api/complaint/controllers"
	repositories2 "kutamukti-api/api/complaint/repositories"
	services2 "kutamukti-api/api/complaint/services"
	controllers6 "kutamukti-api/api/gallery/controllers"
	repositories6 "kutamukti-api/api/gallery/repositories"
	services6 "kutamukti-api/api/gallery/services"
	controllers3 "kutamukti-api/api/schedule/controllers"
	repositories3 "kutamukti-api/api/schedule/repositories"
	services3 "kutamukti-api/api/schedule/services"
	controllers7 "kutamukti-api/api/storages/controllers"
	repositories7 "kutamukti-api/api/storages/repositories"
	services7 "kutamukti-api/api/storages/services"
	controllers5 "kutamukti-api/api/umkm/controllers"
	repositories5 "kutamukti-api/api/umkm/repositories"
	services5 "kutamukti-api/api/umkm/services"
	"kutamukti-api/api/users/controllers"
	"kutamukti-api/api/users/repositories"
	"kutamukti-api/api/users/services"
)

// Injectors from injector.go:

func InitializeUserController(db *gorm.DB, validate *validator.Validate) controllers.CompControllers {
	compRepositories := repositories.NewComponentRepository()
	compServices := services.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers.NewCompController(compServices)
	return compControllers
}

func InitializeComplaintController(db *gorm.DB, validate *validator.Validate) controllers2.CompControllers {
	compRepositories := repositories2.NewComponentRepository()
	compServices := services2.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers2.NewCompController(compServices)
	return compControllers
}

func InitializeScheduleController(db *gorm.DB, validate *validator.Validate) controllers3.CompControllers {
	compRepositories := repositories3.NewComponentRepository()
	compServices := services3.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers3.NewCompController(compServices)
	return compControllers
}

func InitializeAnnouncementController(db *gorm.DB, validate *validator.Validate) controllers4.CompControllers {
	compRepositories := repositories4.NewComponentRepository()
	compServices := services4.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers4.NewCompController(compServices)
	return compControllers
}

func InitializeUMKMController(db *gorm.DB, validate *validator.Validate) controllers5.CompControllers {
	compRepositories := repositories5.NewComponentRepository()
	compServices := services5.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers5.NewCompController(compServices)
	return compControllers
}

func InitializeGalleryController(db *gorm.DB, validate *validator.Validate) controllers6.CompControllers {
	compRepositories := repositories6.NewComponentRepository()
	compServices := services6.NewComponentServices(compRepositories, db, validate)
	compControllers := controllers6.NewCompController(compServices)
	return compControllers
}

func InitializeStorageController(db *gorm.DB, validate *validator.Validate) controllers7.CompControllers {
	compRepositories := repositories7.NewComponentRepository()
	compServices := services7.NewComponentServices(compRepositories, db)
	compControllers := controllers7.NewCompController(compServices)
	return compControllers
}

// injector.go:

var userFeatureSet = wire.NewSet(repositories.NewComponentRepository, services.NewComponentServices, controllers.NewCompController)

var complaintFeatureSet = wire.NewSet(repositories2.NewComponentRepository, services2.NewComponentServices, controllers2.NewCompController)

var scheduleFeatureSet = wire.NewSet(repositories3.NewComponentRepository, services3.NewComponentServices, controllers3.NewCompController)

var announcementFeatureSet = wire.NewSet(repositories4.NewComponentRepository, services4.NewComponentServices, controllers4.NewCompController)

var umkmFeatureSet = wire.NewSet(repositories5.NewComponentRepository, services5.NewComponentServices, controllers5.NewCompController)

var galleryFeatureSet = wire.NewSet(repositories6.NewComponentRepository, services6.NewComponentServices, controllers6.NewCompController)

var storageFeatureSet = wire.NewSet(repositories7.NewComponentRepository, services7.NewComponentServices, controllers7.NewCompController)
